[project]
name = "axp_audit_trail_analyzer"
version = "0.1.0"
description = "A tool to analyze and list data extracted from Avaya AXP APIs."
requires-python = ">=3.9"
dependencies = [
    "httpx==0.27.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
